#
# makefile for OS/2 / GCC 4.x / no SSE2 and AES instructions
#

OPTFLAGS=-O2 -march=i486 -mtune=i686

ALLFLAGS=${OPTFLAGS} -m32 -s -Zomf -Zhigh-mem \
        -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE \
        -DNDEBUG -D_REENTRANT -DENV_UNIX \
        $(LOCAL_FLAGS)

CXX=g++ $(ALLFLAGS)
CC=gcc $(ALLFLAGS)
CC_SHARED=-Zdll
LINK_SHARED=-Zdll
ASM=nasm -f aout

LOCAL_LIBS=-lpthread
LOCAL_LIBS_DLL=$(LOCAL_LIBS)

CPU=x86
OBJ_CRC32=$(OBJ_CRC32_x86)
OBJ_AES=

BINSUFFIX=.exe
SOSUFFIX=.dll

